language: node_js
node_js:
  - "4.4.5"
before_script:
  - npm install -g gulp
script: gulp
before_deploy: "echo 'Prepare to deploy'"
deploy:
  provider: heroku
  buildpack: nodejs
  api_key:
    secure: pzoz8nPTfjwgVH8GCknveY1lxhhUR1VrtVJU6qCgRvunVof5mXqojCwbfwEDyL1u6O8E8jqVU6ZTa8p72g1MR82jsHtk2dDSmgx3P1CwzHvFzl7CdJe6DFJuXHaTNbrJrnQAhaEakQTZSs40cdjN8RNQMUK+ihHy3ZNhuB1kYTCR96IE8BONZ9M0qc1HyddLTD2HNAKkxw9y/xpRtiSLyLRNktcvUJ7t+8xnnoXBDRMbd3gR0PyJ9Os+QgwAS9WS8YDxSUtIOnNPp7YJLhpeNbWbXf4h0MTSSkd1IdZTzdluahPab1JAyRCDVCSy+DgsAZ95CdhHM2ZYAqDp2dtHwHAHbW7GVwWwDBE3IF5BBrLpO8zSJVbHtnsMa0agfYLY35mACz8CxFPL+RqolhQvJyZK21UWI1L+zRER+/2utgp5F1OnZBKz+yubS5A6HtlzEN2vCm7U1Tk9WZlt+xTVozn5lB5rqaPVARS7Jv9nhx+iy0GAnIJkf5cQ0K3gWUM7aGT8UiPH9hmq0wQMxF/enIw32QYGx0fJmRY9eUV+B00F7ju7Nz4AJeiFT6gGpE1Vp2JcY7XY79IUwMTyyWH9CaypbzvsLUGmWeil/wFwWZkFMG1skRpH9Ajre/RSn5zn434yDqvOwi9EFWPj+bPec3OovK/M4cW7mkM7CuXB4kE=
  app: canonshop
  skip_cleanup: true
after_deploy: "echo 'Deploy completed'"
